const { withAppBuildGradle, withProjectBuildGradle, withDangerousMod } = require('expo/config-plugins');
const fs = require('node:fs');
const path = require('node:path');

/**
 * Teaches the generated native projects about the LevelPlay mediation adapters.
 *
 * `ironsource-mediation` autolinks the LevelPlay SDK itself and nothing else. An
 * adapter is what lets a demand network bid, and each one is a separate native
 * dependency the app project has to declare — so without this plugin the app
 * builds, initialises, and then only ever serves ironSource's own inventory.
 * Five networks are wired here: ironSource comes with the SDK, and Unity Ads,
 * AppLovin, Meta Audience Network and Pangle arrive through the adapters below.
 *
 * `android/` and `ios/` are gitignored and regenerated by `expo prebuild`, so a
 * config plugin is the only edit to them that survives.
 *
 * ## Versions are pinned deliberately
 *
 * `ironsource-mediation@3.2.0` pins LevelPlay 8.10.0 on both platforms
 * (`com.unity3d.ads-mediation:mediation-sdk:8.10.0`, pod `IronSourceSDK
 * 8.10.0.0`). The adapters' 5.x line requires LevelPlay 9.x — CocoaPods refuses
 * that outright, and on Android it resolves to a mismatched pair that fails at
 * runtime rather than at build time. So the pins here are the last of the 4.3.x
 * line, which is the one built against 8.x. They move when the plugin moves, not
 * before, and the pairing is worth re-checking against
 * https://developers.is.com/ironsource-mobile/android/mediation-networks-android/
 * whenever either end changes.
 *
 * On Android the adapter artifacts declare no dependencies of their own — their
 * POMs are empty — so each demand network's own SDK is listed here alongside its
 * adapter. Missing one is not a build failure: the adapter simply reports the
 * network as unavailable at init, which reads as poor fill rather than as a bug.
 */

/** Android: adapter → the network SDK it needs, which its POM does not pull in. */
const ANDROID_DEPENDENCIES = [
  // Unity Ads
  "implementation 'com.unity3d.ads-mediation:unityads-adapter:4.3.65'",
  "implementation 'com.unity3d.ads:unity-ads:4.17.0'",
  // AppLovin
  "implementation 'com.unity3d.ads-mediation:applovin-adapter:4.3.55'",
  "implementation 'com.applovin:applovin-sdk:13.4.0'",
  // Meta Audience Network
  "implementation 'com.unity3d.ads-mediation:facebook-adapter:4.3.52'",
  "implementation 'com.facebook.android:audience-network-sdk:6.21.0'",
  // Pangle — the SDK is not on Maven Central; see PANGLE_MAVEN below.
  //
  // The artifact and the version are both narrower than they look, and both
  // were found by running it rather than by reading anything. Pangle's Android
  // SDK ships as `pag-sdk`, not the older `ads-sdk`, whose last release (6.5.1.2)
  // has no `PAGConfig.Builder.setAdxId` — and `pag-sdk` 7.9 and later dropped
  // `setGDPRConsent(int)`. Adapter 4.3.51 calls both, so it only works against
  // 7.1.0.4 … 7.8.6.2, and 7.8.6.2 is the last of those. Either mismatch builds,
  // installs, and then throws `NoSuchMethodError` inside LevelPlay's init on the
  // device, where the SDK catches it — so the symptom is a network that never
  // initialises rather than a crash, and nothing on screen says which.
  //
  // LevelPlay's ad-quality connector supports none of the versions this adapter
  // can use — it says "ByteDance SDK version 7.8.6.2 is not yet supported by the
  // connector" at init, and says the same of 7.5.0.5 and of 8.1.0.7. Ad Quality
  // is revenue measurement rather than delivery, so Pangle still serves; there is
  // simply no version that satisfies both, and picking the newest the adapter
  // accepts is the closest thing to a fix available here.
  "implementation 'com.unity3d.ads-mediation:pangle-adapter:4.3.51'",
  "implementation 'com.pangle.global:pag-sdk:7.8.6.2'",
  // Required by the LevelPlay SDK itself, and not pulled in by it: without these
  // the SDK cannot read the advertising id or the app set id, and every network
  // sees an anonymous request with no device signal at all.
  "implementation 'com.google.android.gms:play-services-appset:16.0.2'",
  "implementation 'com.google.android.gms:play-services-ads-identifier:18.0.1'",
  "implementation 'com.google.android.gms:play-services-basement:18.3.0'"
];

/**
 * Pangle publishes its global Android SDK to ByteDance's own repository rather
 * than to Maven Central. The adapter resolves from Central; the SDK it needs
 * does not, and the failure is a plain "could not find com.pangle.global:pag-sdk".
 */
const PANGLE_MAVEN = 'https://artifact.bytedance.com/repository/pangle';

/** iOS: each pod pulls its own network SDK, so the adapter line is the whole of it. */
const IOS_PODS = [
  "pod 'IronSourceUnityAdsAdapter', '4.3.61.0'",
  "pod 'IronSourceAppLovinAdapter', '4.3.57.0'",
  "pod 'IronSourceFacebookAdapter', '4.3.53.0'",
  "pod 'IronSourcePangleAdapter', '4.3.54.0'"
];

/** Marks our block in a generated file, so a second prebuild does not add it twice. */
const MARKER = 'LevelPlay mediation adapters (plugins/withLevelPlayMediation.js)';

function withAdapterDependencies(config) {
  return withAppBuildGradle(config, (mod) => {
    if (mod.modResults.contents.includes(MARKER)) return mod;
    const block = [`    // ${MARKER}`, ...ANDROID_DEPENDENCIES.map((line) => `    ${line}`)].join('\n');
    // The app module's own `dependencies {` block, which in Expo's template is
    // the last one in the file — anchoring on the first would land in
    // `buildscript`, where an `implementation` line is not even valid.
    const at = mod.modResults.contents.lastIndexOf('dependencies {');
    if (at === -1) throw new Error('withLevelPlayMediation: no dependencies block in app/build.gradle');
    const insert = at + 'dependencies {'.length;
    mod.modResults.contents =
      mod.modResults.contents.slice(0, insert) + '\n' + block + mod.modResults.contents.slice(insert);
    return mod;
  });
}

function withPangleRepository(config) {
  return withProjectBuildGradle(config, (mod) => {
    if (mod.modResults.contents.includes(PANGLE_MAVEN)) return mod;
    const block = `\n        // Pangle's SDK is not on Maven Central. ${MARKER}\n        maven { url '${PANGLE_MAVEN}' }`;
    const at = mod.modResults.contents.indexOf('allprojects {');
    const anchor = mod.modResults.contents.indexOf('repositories {', at === -1 ? 0 : at);
    if (anchor === -1) throw new Error('withLevelPlayMediation: no repositories block in android/build.gradle');
    const insert = anchor + 'repositories {'.length;
    mod.modResults.contents =
      mod.modResults.contents.slice(0, insert) + block + mod.modResults.contents.slice(insert);
    return mod;
  });
}

function withAdapterPods(config) {
  return withDangerousMod(config, [
    'ios',
    (mod) => {
      const podfile = path.join(mod.modRequest.platformProjectRoot, 'Podfile');
      const contents = fs.readFileSync(podfile, 'utf8');
      if (contents.includes(MARKER)) return mod;
      const block = [`  # ${MARKER}`, ...IOS_PODS.map((line) => `  ${line}`)].join('\n');
      // Inside the app target, so the adapters link into the app binary rather
      // than into a pod target that nothing depends on.
      const target = contents.match(/^target ['"].*['"] do$/m);
      if (target === null) throw new Error('withLevelPlayMediation: no app target in the Podfile');
      const insert = contents.indexOf(target[0]) + target[0].length;
      fs.writeFileSync(podfile, contents.slice(0, insert) + '\n' + block + contents.slice(insert));
      return mod;
    }
  ]);
}

module.exports = function withLevelPlayMediation(config) {
  return withAdapterPods(withPangleRepository(withAdapterDependencies(config)));
};
