export const IPC_CHANNELS = {
  getSettings: 'settings:get',
  listSources: 'sources:list',
  selectSource: 'sources:select',
  getSelectedSource: 'sources:selected',
  checkSelectedSource: 'sources:check-selected',
  startRecording: 'recording:start',
  appendRecordingChunk: 'recording:append-chunk',
  finishRecording: 'recording:finish',
  abortRecording: 'recording:abort',
  openResult: 'result:open',
  revealResult: 'result:reveal',
  voiceProfilesList: 'voice-profiles:list',
  voiceProfilesStart: 'voice-profiles:start',
  voiceProfilesAppend: 'voice-profiles:append',
  voiceProfilesFinalize: 'voice-profiles:finalize',
  voiceProfilesDiscard: 'voice-profiles:discard',
  voiceProfilesDelete: 'voice-profiles:delete',
  getTtsRuntimeStatus: 'tts:runtime-status',
  startTtsJob: 'tts:start-job',
  getTtsJob: 'tts:get-job',
  openTtsResult: 'tts:open-result',
  revealTtsResult: 'tts:reveal-result',
  projectsList: 'projects:list',
  projectsCreate: 'projects:create',
  projectsOpen: 'projects:open',
  projectsDelete: 'projects:delete',
  projectAssetsImport: 'project-assets:import',
  projectRecordingResultImport: 'project-assets:import-recording-result',
  projectTtsResultImport: 'project-assets:import-tts-result',
  projectAssetMetadataUpdate: 'project-assets:update-metadata',
  projectAssetPlaybackUrl: 'project-assets:playback-url',
  projectTimelineSave: 'project-timeline:save',
  startExportJob: 'export:start-job',
  getExportJob: 'export:get-job',
  cancelExportJob: 'export:cancel-job',
  openExportResult: 'export:open-result',
  revealExportResult: 'export:reveal-result',
  timelineMenuCommand: 'timeline-menu:command',
  timelineMenuState: 'timeline-menu:state',
  aiGenerateVideo: 'ai:generate-video',
  aiGetVideoJob: 'ai:get-video-job',
  aiGenerateSpeech: 'ai:generate-speech',
  aiGetSpeechJob: 'ai:get-speech-job',
  projectAiResultImport: 'project-assets:import-ai-result'
} as const;

export type IpcChannel = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS];
