/**
 * Shot planning for a scenario, done in code.
 *
 * The arithmetic here is the part a model reliably gets wrong: providers accept
 * only certain clip lengths (Sora 4/8/12s, Veo 4-8s), so "make me a 30 second
 * video" has to become a shot list whose durations are all individually legal
 * and which still adds up. Left to the model, that produces jobs the provider
 * rejects after the user has already approved the spend.
 */

/** Clip lengths each engine will actually accept, by domain-model provider id. */
const SUPPORTED_SHOT_SECONDS: Readonly<Record<string, readonly number[]>> = {
  openai: [4, 8, 12],
  google_gemini: [4, 6, 8],
  byteplus: [5, 10]
};

const FALLBACK_SHOT_SECONDS: readonly number[] = [4, 8];

export function supportedShotSeconds(providerId: string): readonly number[] {
  return SUPPORTED_SHOT_SECONDS[providerId] ?? FALLBACK_SHOT_SECONDS;
}

/**
 * The longest shot any engine accepts. The createVideoJob schema derives its
 * upper bound from this rather than carrying its own number: a schema that
 * rejected a length the planner emits would fail a shot the user had already
 * priced and approved, which is the exact failure the planner exists to stop.
 */
export const MAX_SUPPORTED_SHOT_SECONDS: number = Math.max(
  ...Object.values(SUPPORTED_SHOT_SECONDS).flatMap((options) => [...options]),
  ...FALLBACK_SHOT_SECONDS
);

/**
 * Continuity is what separates a scenario from a pile of clips. Each shot is
 * generated by a separate provider call with no memory of the others, so
 * anything that must stay the same has to be restated in every prompt.
 */
export const CONTINUITY_KEYS = ['subject', 'wardrobe', 'props', 'location', 'lighting', 'lens'] as const;

export type ContinuityKey = (typeof CONTINUITY_KEYS)[number];

export type PlannedShot = {
  readonly index: number;
  readonly durationSeconds: number;
  readonly startSeconds: number;
};

export type StoryboardPlan = {
  readonly shots: readonly PlannedShot[];
  readonly totalSeconds: number;
  readonly requestedSeconds: number;
  /** Set when the shot lengths cannot sum to exactly what was asked for. */
  readonly roundedFrom?: number;
  readonly providerId: string;
  readonly supportedShotSeconds: readonly number[];
  readonly continuityKeys: readonly ContinuityKey[];
};

/** Hard ceiling so a mistyped length cannot queue hundreds of paid jobs. */
export const MAX_PLANNED_SHOTS = 24;

/**
 * Fills `totalSeconds` with the longest legal shots first, so a 30s request
 * becomes fewer, longer clips rather than a swarm of minimum-length ones —
 * fewer provider calls, fewer seams to match, and usually cheaper.
 */
export function planVideoStoryboard(input: {
  readonly totalSeconds: number;
  readonly providerId: string;
}): StoryboardPlan {
  const options = [...supportedShotSeconds(input.providerId)].sort((a, b) => b - a);
  const longest = options[0] ?? 8;
  const shortest = options[options.length - 1] ?? 4;

  const requested = Math.max(shortest, Math.round(input.totalSeconds));
  const capped = Math.min(requested, longest * MAX_PLANNED_SHOTS);

  const durations: number[] = [];
  let remaining = capped;
  while (remaining > 0 && durations.length < MAX_PLANNED_SHOTS) {
    // Prefer an exact finish; otherwise take the longest shot that fits, and
    // fall back to the shortest legal length for the final remainder.
    const exact = options.find((option) => option === remaining);
    const fits = options.find((option) => option <= remaining);
    const chosen = exact ?? fits ?? shortest;
    durations.push(chosen);
    remaining -= chosen;
  }

  let startSeconds = 0;
  const shots = durations.map((durationSeconds, offset) => {
    const shot: PlannedShot = { index: offset + 1, durationSeconds, startSeconds };
    startSeconds += durationSeconds;
    return shot;
  });

  const totalSeconds = durations.reduce((sum, seconds) => sum + seconds, 0);

  return {
    shots,
    totalSeconds,
    requestedSeconds: Math.round(input.totalSeconds),
    // Only reported when it actually differs, so a clean plan says nothing.
    ...(totalSeconds === Math.round(input.totalSeconds) ? {} : { roundedFrom: Math.round(input.totalSeconds) }),
    providerId: input.providerId,
    supportedShotSeconds: supportedShotSeconds(input.providerId),
    continuityKeys: CONTINUITY_KEYS
  };
}
